import Head from 'next/head'
import { Inter } from '@next/font/google'
import Navbar from "../Components/Navbar"
import Footer from "../Components/footer";
import Landing from "../Components/Landing";
import {ClickerPannier} from '../feature/main/mainSlice'
import { useDispatch, useSelector } from "react-redux";
import Pannier from "../Components/Pannier/pannier";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const PannierC=useSelector((state:any)=>state.main.PannierClicked)
  const dispatch=useDispatch()
  const direction=useSelector((state:any)=>state.main.dir)
  let ages = [
   {id:0,title:'a'},{id:1,title:'b'},
   {id:2,title:'c'},{id:3,title:'d'},{id:4,title:'e'}
   ];
   
console.log(direction);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-2">
        <div  className="font-['Montserrat'] bg-[#F5F5F5] "  dir={`${direction ? 'ltr' : 'rtl'}`}>
              { PannierC &&    <div className="fixed top-0 left-0 bottom-0 right-0 w-full grid place-content-center z-10 h-[100vh] bg-[#00000045]  "
              // onClick={()=>dispatch(ClickerPannier())}
              >
            <Pannier></Pannier>
              </div>
                  }
              <Navbar Home={true}></Navbar>
              <Landing></Landing>
              <Footer></Footer>
      </div>
  
      </main>
    </>
  )
}
